/* apiVersion: apps/v1 */
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
         name: train-cicd
         labels:
           app: train-v2
spec:
  replicas: 1 
  selector: 
     matchLabels:
             app: train-v1
  template:
     metadata:
       labels:
          app: train-v1
     spec:
       containers:
       - name: train-cicd
         image: singhparul/mydevopstest:5
         ports:
         - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: train-svc
  labels:
    app: train-v1
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 32013
  selector:
    app: app-v1
