apiVersion: apps/v1 
kind: Deployment
metadata: 
         name: train-cicd-v2
         labels:
           app: train-v2
spec:
  replicas: 1 
  selector: 
     matchLabels:
             app: train-v2
  template:
     metadata:
       labels:
          app: train-v2
     spec:
       containers:
       - name: train-cicd-v2
         image: singhparul/mydevopstest:5
         ports:
         - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: train-svc-v2
  labels:
    app: train-v2
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 32020
  selector:
    app: train-v2
